Homework js2 week2
Pallabi-ghosh/hyf-homework pull request #10
Opened 2020-06-19 12:28 UTC by Pallabi-ghosh

2020-06-21 10:40 UTC, flom84 requested changes
For the movies exercise, please not include all the movies array...it's 40000 lines. is not okay...you should not make your own movies variable. Instead include javascript2/week2/homework/movies.js into your .html file

2020-06-22 17:13 UTC, braedongough approved these changes
Great work!

2020-06-22 17:13 UTC, braedongough commented on javascript/javascript2/week2/movie_function.js
> +console.log(moviesWithSpecialWords)
It doesn;t look like you're invoking the function here, that could be the cause of some of your problems: 
```suggestion
console.log(moviesWithSpecialWords())
```

2020-06-22 17:13 UTC, braedongough commented on javascript/javascript2/week2/movie_function.js
> +}
As promise, here's how I would solve this one: 
```js
const numberOfMoviesWithKeyWords = (keywords) => {
  return movies.filter((movie) => {
    return keywords.some((keyword) => movie.title.includes(keyword))
  }).length
}

console.log(
  'numberOfMoviesWithKeyWords',
  numberOfMoviesWithKeyWords(['Alien', 'gai'])
)

```

The function I've created above allows you to pass any array of keywords to check against. I recommend you read into the `.some` array method. As you continue on you'll need to start reaching for some new tools to help with some more tricky problems  🤠 
 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2020-06-22 17:13 UTC, braedongough commented on javascript/javascript2/week2/movie_function.js
> +    return movies.reduce(function(prevWord, currWord) {
Nice use of reduce! Reduce is a tricky method to learn so make sure to double check you've got the right solution here. It looks good from what I can see. See if you can refactor this to use an arrow function!

2020-06-22 17:13 UTC, braedongough commented on javascript/javascript2/week2/main.js
> +console.log(productsUl);
Remember to remove console logs that you only use for debugging from your final submission!

2020-06-22 17:13 UTC, braedongough commented on javascript/javascript2/week2/main.js
> +    let inputadd = document.querySelector('input');
You've already selected this above, you can reuse the same variable `input`!

2020-06-25 05:58 UTC, merged